### ISSUE TITLE
Unexpected Object Type when parsing files

### ISSUE THREAD

**Issue by TMo484** [wayfair-incubator/pyterraformer#14]
Why does the `comment` parser return a list instead of a TerraformObject? 

https://github.com/wayfair-incubator/pyterraformer/blob/bd8b31405ab5949fea24ea76c59793c368485eab/pyterraformer/serializer/human_resources/engine.py#L327

[When parsing](https://github.com/wayfair-incubator/pyterraformer/blob/main/pyterraformer/core/namespace.py#L149) through resources of a given file, we are expecting there to be a `_type` which is present on the `Comment` class; but that is found on the second element in the array. I feel like the purpose of this was to be able to identify a comment by it's row (likely for modification); but I think we should instead check for `_type` and then check metadata for `start_pos` (or something like that). This would keep us consistent with modifying actual ResourceObjects (where we check `_type` and then check `tf_id`).

That way, we could reliably return a list of TerraformObjects and ensure that we're properly handling any downstream checks / assignments. Thoughts?

For example, here is a list from an existing `resource.tf` file I have (each object is displaying by printing the type() and then the value)

```
['comment-0', comment(text="//")]
<class 'list'>
['comment-3', comment(text="//   Any of the Terraform modules can be utilized here as well as Terraform")]
<class 'list'>
['comment-79', comment(text="//   `resource` and `data` statements.")]
<class 'pyterraformer.core.resources.resource_object.ResourceObject'>
google_service_account(account_id="var.dataproc_service_account_name", display_name="var.dataproc_service_account_name", project="var.gcp_project_us")
<class 'pyterraformer.core.modules.ModuleObject'>
module(source=""https://artifactory.service.bo1.csnzoo.com/artifactory/terraform/modules/tf-mod-google-dataproc-cluster/tf-mod-google-dataproc-cluster_v3.0.2.tar.gz"", name=""tmori-test-cluster"", project="var.gcp_project_us", wayfair_vpc="var.dataproc_subnet["subnet_vpc_name"]", subnetwork="var.dataproc_subnet["subnet_name"]", region="local.region", service_account_email=""${var.dataproc_service_account_name}@${var.gcp_project_us}.iam.gserviceaccount.com"", comment-831="comment(text="#metastore_connection is utilizing the main dataproc_prod connection")", hive_metastore_connection_name="var.dataproc_metastore_connection", hive_warehouse_bucket="var.dataproc_warehouse_bucket", comment-1033="comment(text="#kms_key taken from ds_catalog_dataproc; will obviously need to be replaced")", hive_credential_kms_key=""projects/wf-gcp-us-ae-dataproc-prod/locations/us-central1/keyRings/hadoop-key-ring/cryptoKeys/hive-key"", labels="{}", history_bucket="var.dataproc_history_bucket", staging_bucket="var.dataproc_staging_bucket", autoscaling_enable="false")
<class 'list'>
['comment-1392', comment(text="# granting this custom SA ephemeral dataproc worker role; as it is the only custom role with the correct perms")]
<class 'list'>
['comment-1503', comment(text="# this should be changed to dataproc.worker when possible")]
<class 'pyterraformer.core.resources.resource_object.ResourceObject'>
google_project_iam_member(project="var.gcp_project_us", role=""organizations/825417849120/roles/tf_wf_ae_svc_ephemeral_dataproc_worker"", member=""serviceAccount:${var.dataproc_service_account_name}@${var.gcp_project_us}.iam.gserviceaccount.com"")
<class 'pyterraformer.core.resources.resource_object.ResourceObject'>
```

The error I receive is:
```
  File "C:\Users\tmori\AppData\Roaming\JetBrains\PyCharmCE2021.1\scratches\tmori_test_scratch.py", line 31, in <module>
    namespace.add_object(GoogleStorageBucket(
  File "C:\Users\tmori\wayfair-incubator\pyterraformer\pyterraformer\core\namespace.py", line 151, in add_object
    indexes = [
  File "C:\Users\tmori\wayfair-incubator\pyterraformer\pyterraformer\core\namespace.py", line 152, in <listcomp>
    idx for idx, val in enumerate(self.objects) if val._type == object._type
AttributeError: 'list' object has no attribute '_type'
```

**Comment by TMo484** [comment]
For example, here is a list from an existing `resource.tf` file I have (each object is displaying by printing the `type()` and then the `value`)
```<class 'list'>
['comment-0', comment(text="//")]
<class 'list'>
['comment-3', comment(text="//   Any of the Terraform modules can be utilized here as well as Terraform")]
<class 'list'>
['comment-79', comment(text="//   `resource` and `data` statements.")]
<class 'pyterraformer.core.resources.resource_object.ResourceObject'>
google_service_account(account_id="var.dataproc_service_account_name", display_name="var.dataproc_service_account_name", project="var.gcp_project_us")
<class 'pyterraformer.core.modules.ModuleObject'>
module(source=""https://artifactory.service.bo1.csnzoo.com/artifactory/terraform/modules/tf-mod-google-dataproc-cluster/tf-mod-google-dataproc-cluster_v3.0.2.tar.gz"", name=""tmori-test-cluster"", project="var.gcp_project_us", wayfair_vpc="var.dataproc_subnet["subnet_vpc_name"]", subnetwork="var.dataproc_subnet["subnet_name"]", region="local.region", service_account_email=""${var.dataproc_service_account_name}@${var.gcp_project_us}.iam.gserviceaccount.com"", comment-831="comment(text="#metastore_connection is utilizing the main dataproc_prod connection")", hive_metastore_connection_name="var.dataproc_metastore_connection", hive_warehouse_bucket="var.dataproc_warehouse_bucket", comment-1033="comment(text="#kms_key taken from ds_catalog_dataproc; will obviously need to be replaced")", hive_credential_kms_key=""projects/wf-gcp-us-ae-dataproc-prod/locations/us-central1/keyRings/hadoop-key-ring/cryptoKeys/hive-key"", labels="{}", history_bucket="var.dataproc_history_bucket", staging_bucket="var.dataproc_staging_bucket", autoscaling_enable="false")
<class 'list'>
['comment-1392', comment(text="# granting this custom SA ephemeral dataproc worker role; as it is the only custom role with the correct perms")]
<class 'list'>
['comment-1503', comment(text="# this should be changed to dataproc.worker when possible")]
<class 'pyterraformer.core.resources.resource_object.ResourceObject'>
google_project_iam_member(project="var.gcp_project_us", role=""organizations/825417849120/roles/tf_wf_ae_svc_ephemeral_dataproc_worker"", member=""serviceAccount:${var.dataproc_service_account_name}@${var.gcp_project_us}.iam.gserviceaccount.com"")
<class 'pyterraformer.core.resources.resource_object.ResourceObject'>
```

The error I receive is:
```Traceback (most recent call last):
  File "C:\Users\tmori\AppData\Roaming\JetBrains\PyCharmCE2021.1\scratches\tmori_test_scratch.py", line 31, in <module>
    namespace.add_object(GoogleStorageBucket(
  File "C:\Users\tmori\wayfair-incubator\pyterraformer\pyterraformer\core\namespace.py", line 151, in add_object
    indexes = [
  File "C:\Users\tmori\wayfair-incubator\pyterraformer\pyterraformer\core\namespace.py", line 152, in <listcomp>
    idx for idx, val in enumerate(self.objects) if val._type == object._type
AttributeError: 'list' object has no attribute '_type'
```

**Comment by greenmtnboy** [comment]
This almost certainly relates to some original hacky handling to make sure that comments were re-serialized back to the correct location, since they can appear in arbitrary locations within other terraform objects. Do you have a basic sanitized example you could add on here to show the problem? Almost certainly a better to handle it, I think the addition of the metadata context on each object is where we want this.

**Comment by greenmtnboy** [comment]
@TMo484 can you approve the PR?

**Comment by TMo484** [comment]
Approved
